services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/ecom_app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=sqlite:///db.sqlite3