# Generated by Django 5.1.4 on 2024-12-22 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_useraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
    ]
