# Generated by Django 5.1.4 on 2024-12-22 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_profile_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='updated',
            new_name='modified_at',
        ),
    ]
